### ISSUE TITLE
History serialization issue - using JacksonSerializer or JavaSerializer

### ISSUE THREAD

**Issue by sterlp** [bekk/db-scheduler-ui#107]
Currently you may specify a serialization strategy. If you choose JSON/Jackson you get following error:

```
java.io.StreamCorruptedException: invalid stream header: 7B226F72
	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:989) ~[na:na]
	at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:416) ~[na:na]
	at org.springframework.util.SerializationUtils.deserialize(SerializationUtils.java:82) ~[spring-core-6.1.6.jar:6.1.6]
	at no.bekk.dbscheduler.ui.model.LogModel.stringTaskData(LogModel.java:64) ~[db-scheduler-ui-1.1.2.jar:na]
	at no.bekk.dbscheduler.ui.model.LogModel.<init>(LogModel.java:51) ~[db-scheduler-ui-1.1.2.jar:na]
	at no.bekk.dbscheduler.ui.service.LogLogic$LogModelRowMapper.mapRow(LogLogic.java:209) ~[db-scheduler-ui-1.1.2.jar:na]
	at no.bekk.dbscheduler.ui.service.LogLogic$LogModelRowMapper.mapRow(LogLogic.java:189) ~[db-scheduler-ui-1.1.2.jar:na]
```

The issue is, that the current code assume both, Java Serialization and Jackson object mapping:

```java
  private Object stringTaskData(byte[] inputTaskData) {
    try {
      if (inputTaskData != null) {
        Object dataclass = SerializationUtils.deserialize(inputTaskData);
        String serializedData = objectMapper.writeValueAsString(dataclass);
        return objectMapper.readValue(serializedData, Object.class);
      }
    } catch (IOException e) {
      throw new RuntimeException(e);
    }
    return null;
  }
```
 but as far I can tell it can only be one of each other:

![image](https://github.com/bekk/db-scheduler-ui/assets/774984/0537033a-6e15-4487-8a1d-71a5acb8b53f)

My current hotfix looks like:

```java
  @Slf4j
  @RequiredArgsConstructor
  private static class LogModelRowMapper implements RowMapper<LogModel> {
    private final boolean showData;
    private final ObjectMapper objectMapper;
    @Override
    public LogModel mapRow(@NonNull ResultSet rs, int rowNum) throws SQLException {
      Object taskData = null;
      if (showData) {
         final byte[] raw = rs.getBytes("task_data");
         try {
          if (raw != null) taskData = objectMapper.readValue(raw, Object.class);
        } catch (Exception e) {
          log.warn("Could not deserialize task data name={}", rs.getString("task_name"), e);
        }
      }

      return new LogModelFixed(
          rs.getLong("id"),
          rs.getString("task_name"),
          rs.getString("task_instance"),
          taskData,
          rs.getTimestamp("time_started").toInstant(),
          rs.getTimestamp("time_finished").toInstant(),
          rs.getBoolean("succeeded"),
          rs.getLong("duration_ms"),
          rs.getString("exception_class"),
          rs.getString("exception_message"),
          rs.getString("exception_stacktrace"));
    }
  }
```

**Comment by geirsagberg** [comment]
I agree, the serializer definitely should have been injected, and the spring boot starter should use the DbSchedulerCustomizer, as in https://github.com/rocketbase-io/db-scheduler-log/blob/main/db-scheduler-log-boot-starter/src/main/java/io/rocketbase/extension/boot/autoconfigure/DbSchedulerLogAutoConfiguration.java#L72.  Open to a PR :D

**Comment by ElectroLutz** [comment]
I'm looking forward to a release of this fix, since we're expieriencing the same bug.

**Comment by sterlp** [comment]
@geirsagberg here you go: https://github.com/bekk/db-scheduler-ui/pull/109

**Comment by geirsagberg** [comment]
Nice, will take a look tonight!

**Comment by sterlp** [comment]
thanks works like a charm.
