### ISSUE TITLE
UI is crashing when there is no scheduled executions in response

### ISSUE THREAD

**Issue by ipodobin** [bekk/db-scheduler-ui#114]
UI is crashing where there is no results in response. With console error:
>TypeError: Cannot read properties of undefined (reading 'map')
    at index-8c715290.js:431:16484
    at Array.map (<anonymous>)
    at mm (index-8c715290.js:431:16469)
    at Xg (index-8c715290.js:38:19520)
    at Xm (index-8c715290.js:40:3139)
    at sT (index-8c715290.js:40:44734)
    at oT (index-8c715290.js:40:39724)
    at $R (index-8c715290.js:40:39652)
    at Rd (index-8c715290.js:40:39506)
    at lv (index-8c715290.js:40:35874)

Request:
>db-scheduler-api/tasks/all?filter=FAILED&size=10&sorting=DEFAULT&asc=true&refresh=true&taskNameExactMatch=false&taskInstanceExactMatch=false

>

Response:
>{"numberOfItems":0,"numberOfPages":0}

**Comment by kagkarlsson** [comment]
(Needs reproduction)

**Comment by kagkarlsson** [comment]
Closing as stale
